### ISSUE TITLE
Get mails from multiples pop3 fails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#251] opened 2016-04-25 20:50 UTC
**Originally by _enzobarba@libero.it_ on 2011-01-25 07:58:47 +0100**

___
## Summary
With multiples pop3, "get" action with remote preselect ON, fails

## Steps to reproduce
simply:
(before, active preselect mails on pop3)
1. "Get"
2. YAM scans correctly for the whole pop3 list, also showing the mails' infos, but then exit and return to the main window WITHOUT wait for any user's action or request
3. so, I'm unable to get new mails

## Expected results
On each pop3, wait for a user action (delete/get/get and delete/Cancel/Go)

## Regression
This happens from the YAM2.7-dev ChangeLog 5596 2011-01-20, maybe because the changes on the Signals in tcp/Connection.c

- tcp/Connection.c: gethostbyname() is now protected by a timeout in case the
  network infinitely tries to resolve the host name without returning failure
  within the desired time

## Notes
My system is Pesagos2PPC MOS 1.4.5 and latest Ambient Nightly

**Comment by tboeckel** [comment] 2016-04-25 20:50
**Originally on 2011-01-25 08:04:15 +0100**

___
This is a duplicate of the already fixed ticket #248.

**Closed by tboeckel** 2016-04-25 20:50 UTC
Labels: #major, @undecided, bug, duplicate, nightly build, TCP/IP
