### ISSUE TITLE
Columns in mail transfer window cannot be saved.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#153] opened 2016-04-25 19:59 UTC
**Originally by _hypexed@yahoo.com.au_ on 2010-04-10 18:46:44 +0200**

___
Hello. I installed YAM 2.6 using the installer and replaced YAM 2.5 on my OS4.1u1 A1 system. 

I found that the columns in the mail transfer window were all messed up and my settings for these were erased! What's more after adjusting the columns they cannot be saved. I have tried the snapshot option in the window titlebar gadget. It saves something but next time the window opens YAM has reset the columns again!

I also have other options set such as MUI to save windows on exit. What's going on?

**Comment by tboeckel** [comment] 2016-04-25 19:59
**Originally on 2010-09-29 08:16:13 +0200**

___
Setting the milestone to YAM 2.8 for the moment, as saving the column width of a dynamically created window is not exactly simple. This is due to how MUI itself handles such data as it only exports information about "living" objects. Thus you may snapshot the window (and hereby the columns' width), but the next time you snapshot anything else while the preselection window is not open will drop the previously saved information.

**Comment by tboeckel** [comment] 2016-04-25 19:59
**Originally on 2010-10-27 13:01:21 +0200**

___
As a duplicate of the now fixed ticket #60 this one can be closed as well.

**Closed by tboeckel** 2016-04-25 19:59 UTC
Labels: #minor, @normal, bug, duplicate, GUI, v2.6
