### ISSUE TITLE
yam68k

### ISSUE THREAD

**Issue by yam68k** [jens-maus/yam#627] opened 2016-05-14 13:22 UTC
why do you close the issue, without letting me answer?
here is what i was about to say:

hello,

that was quick. well, it is not about speed, it is about quality and usability.

i already tried myself, basicaly i changed src/Makefile:
 #CPU = -m68020-60 -msoft-float
 CPU = -m68000

is this enough?

there were some other issues, but it did compile ( crosscompiler toolchain in cygwin )
 eg: yam-2.9p1-68k/src/DynamicString.c missing a #include "extrasrc.h"

i think the mayor trouble is yam-2.9p1/src/lib/os3/libm.a, i had to replace with one, which came with the toolchain (there were some unresolved functions).
 is this libm.a compiled for 020+ ? do i have to find a version for 68000 ?

best regards,
 yam68k

**Comment by jens-maus** [comment] 2016-05-14 13:51
You can even comment on closed issues. So please stop opening new issue after another. do this is a duplicate of #626. Closing it therefore as well. So please, if you insist continue to post replies to #626 instead.

**Closed by jens-maus** 2016-05-14 13:51 UTC
