### ISSUE TITLE
Allow to set "preview" for each account seperately

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#97] opened 2016-04-25 19:48 UTC
**Originally by _mario@cattaneo.de_ on 2010-03-04 21:55:04 +0100**

___
It would be nice if the settings for each pop3-account would have a setting, to set the preview/maillist-display for. E.g. I have some accounts I only like to check for content and don't download them immediately. And it's not so convinient, when I have to change the global prefs every time.

**Comment by tboeckel** [comment] 2016-04-25 19:48
**Originally on 2010-12-18 00:07:22 +0100**

___
Duplicate of #46.

**Closed by tboeckel** 2016-04-25 19:48 UTC
Labels: #major, @undecided, duplicate, enhancement
