### ISSUE TITLE
Attached files are broken

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#350] opened 2016-04-25 21:40 UTC
**Originally by _fernandez_jesus@yahoo.fr_ on 2012-10-04 02:51:06 +0200**

___
## Summary

Attached files are boken: more informations.

## Steps to reproduce
 1.
 2.

## Notes
I am sorry. I forgot to give some details.
I am using YAM on SAM FLEX and OS4.1.4.

The problem is during the decoding of files.
After sending some mails to myself with newer versions of YAM, I can't display or use the attached files but when I reinstalled YAM2.7 (i.e. I only copy the exe over nightly build exe), I read these mails without any problems. So the network connections can be discarded.

**Comment by tboeckel** [comment] 2016-04-25 21:40
**Originally on 2012-10-04 02:52:12 +0200**

___
Duplicate of #349.

**Closed by tboeckel** 2016-04-25 21:40 UTC
Labels: #major, @undecided, bug, duplicate, nightly build
