### ISSUE TITLE
PGP Problem when sending Mail

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#430] opened 2016-04-25 23:09 UTC
**Originally by _starkillers@web.de_ on 2013-09-21 20:56:20 +0200**

___
Description: 
I tried PGP 5.0i on my A4000T /OS3.9 /68060 / with YAM 2.8p1
when trying to send the email an error message appears :
Error trying to add the file : ram:t/YAMtxxxx.asc
make sure the file exists 

ok .. the file isnt there !

on my morphos pc it comes to high cpu usage when trying to send a signed or encrypted email an yam freezes.

**Comment by tboeckel** [comment] 2016-04-25 23:09
**Originally on 2013-09-21 20:57:24 +0200**

___
This is a duplicate of #427.

**Closed by tboeckel** 2016-04-25 23:09 UTC
Labels: #major, @undecided, bug, duplicate, Encryption, v2.8
