### ISSUE TITLE
Proper support for List-headers

### ISSUE THREAD

**Issue by cpm1** [jens-maus/yam#646] opened 2016-10-26 10:35 UTC
YAM's so-called "mailing list" support is actually not up to the task of being used with mailing lists configured to meet todays standards (RFC2369, RFC2822) and needs (because of DMARC, DKIM).

Therefore YAM needs support for the List-headers providing the user a proper way to "reply" (to the original author only), "reply to all" (author *and* list) and "reply to list" (list only). This would render the old "mailing list" feature obsolete for correctly configured lists.

**Comment by jens-maus** [comment] 2016-10-26 11:15
This is actually duplicate of https://github.com/jens-maus/yam/issues/124 where I already documented that the mailing list support in YAM requires a large overhaul. So please continue your discussion there instead.

**Closed by jens-maus** 2016-10-26 11:15 UTC
