### ISSUE TITLE
More signatures

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#44] opened 2016-04-25 19:07 UTC
**Originally by _amispatra@users.sourceforge.net_ on 2010-03-03 23:05:04 +0100**

___
I think what YAM could offers more signatures: three seems very few if you are in several mailing-lists (as my case).

**Comment by tboeckel** [comment] 2016-04-25 19:07
**Originally on 2012-07-25 12:24:49 +0200**

___
Duplicate of #307. YAM now supports an unlimited amount of signatures.

**Closed by tboeckel** 2016-04-25 19:07 UTC
Labels: #major, @undecided, duplicate, enhancement
